# ── Nifty 500 Universe ─────────────────────────────────────────────────────────
NIFTY500 = {
    # Nifty 50
    "RELIANCE":      {"name": "Reliance Industries",         "base": 1339},
    "HDFCBANK":      {"name": "HDFC Bank",                   "base": 1771},
    "ICICIBANK":     {"name": "ICICI Bank",                  "base": 1244},
    "INFY":          {"name": "Infosys",                     "base": 1619},
    "TCS":           {"name": "TCS",                         "base": 3267},
    "BHARTIARTL":    {"name": "Bharti Airtel",               "base": 1932},
    "SBIN":          {"name": "State Bank of India",         "base": 861},
    "ITC":           {"name": "ITC",                         "base": 432},
    "LT":            {"name": "Larsen & Toubro",             "base": 3541},
    "AXISBANK":      {"name": "Axis Bank",                   "base": 1235},
    "KOTAKBANK":     {"name": "Kotak Mahindra Bank",         "base": 2175},
    "HINDUNILVR":    {"name": "Hindustan Unilever",          "base": 2345},
    "ASIANPAINT":    {"name": "Asian Paints",                "base": 2636},
    "MARUTI":        {"name": "Maruti Suzuki",               "base": 11200},
    "BAJFINANCE":    {"name": "Bajaj Finance",               "base": 923},
    "WIPRO":         {"name": "Wipro",                       "base": 310},
    "HCLTECH":       {"name": "HCL Technologies",            "base": 1490},
    "TITAN":         {"name": "Titan Company",               "base": 3340},
    "ULTRACEMCO":    {"name": "UltraTech Cement",            "base": 9800},
    "NESTLEIND":     {"name": "Nestle India",                "base": 2250},
    "POWERGRID":     {"name": "Power Grid Corp",             "base": 335},
    "NTPC":          {"name": "NTPC",                        "base": 392},
    "ONGC":          {"name": "ONGC",                        "base": 280},
    "JSWSTEEL":      {"name": "JSW Steel",                   "base": 930},
    "TATAMOTORS":    {"name": "Tata Motors",                 "base": 760},
    "TATASTEEL":     {"name": "Tata Steel",                  "base": 165},
    "HINDALCO":      {"name": "Hindalco Industries",         "base": 665},
    "COALINDIA":     {"name": "Coal India",                  "base": 455},
    "BAJAJFINSV":    {"name": "Bajaj Finserv",               "base": 1746},
    "ADANIENT":      {"name": "Adani Enterprises",           "base": 2739},
    "ADANIPORTS":    {"name": "Adani Ports",                 "base": 1788},
    "CIPLA":         {"name": "Cipla",                       "base": 1550},
    "DRREDDY":       {"name": "Dr Reddy's Labs",             "base": 6800},
    "SUNPHARMA":     {"name": "Sun Pharma",                  "base": 1825},
    "APOLLOHOSP":    {"name": "Apollo Hospitals",            "base": 8056},
    "DIVISLAB":      {"name": "Divi's Laboratories",         "base": 4800},
    "EICHERMOT":     {"name": "Eicher Motors",               "base": 4650},
    "HEROMOTOCO":    {"name": "Hero MotoCorp",               "base": 4200},
    "BAJAJ-AUTO":    {"name": "Bajaj Auto",                  "base": 10171},
    "M&M":           {"name": "Mahindra & Mahindra",         "base": 2950},
    "TECHM":         {"name": "Tech Mahindra",               "base": 1620},
    "HDFCLIFE":      {"name": "HDFC Life Insurance",         "base": 625},
    "SBILIFE":       {"name": "SBI Life Insurance",          "base": 1680},
    "GRASIM":        {"name": "Grasim Industries",           "base": 2650},
    "INDUSINDBK":    {"name": "IndusInd Bank",               "base": 995},
    "TATACONSUM":    {"name": "Tata Consumer Products",      "base": 1020},
    "BRITANNIA":     {"name": "Britannia Industries",        "base": 5450},
    "BPCL":          {"name": "BPCL",                        "base": 315},
    "SHRIRAMFIN":    {"name": "Shriram Finance",             "base": 3450},
    "VEDL":          {"name": "Vedanta",                     "base": 455},
    # Nifty Next 50
    "ADANIGREEN":    {"name": "Adani Green Energy",          "base": 1200},
    "ADANIPOWER":    {"name": "Adani Power",                 "base": 580},
    "ATGL":          {"name": "Adani Total Gas",             "base": 750},
    "AWL":           {"name": "Adani Wilmar",                "base": 320},
    "AMBUJACEM":     {"name": "Ambuja Cements",              "base": 580},
    "BAJAJHLDNG":    {"name": "Bajaj Holdings",              "base": 9500},
    "BANKBARODA":    {"name": "Bank of Baroda",              "base": 240},
    "BERGEPAINT":    {"name": "Berger Paints",               "base": 520},
    "BEL":           {"name": "Bharat Electronics",          "base": 280},
    "BHEL":          {"name": "Bharat Heavy Electricals",    "base": 240},
    "BOSCHLTD":      {"name": "Bosch",                       "base": 32000},
    "CANBK":         {"name": "Canara Bank",                 "base": 105},
    "CHOLAFIN":      {"name": "Cholamandalam Investment",    "base": 1350},
    "COLPAL":        {"name": "Colgate-Palmolive",           "base": 2800},
    "DLF":           {"name": "DLF",                         "base": 780},
    "DABUR":         {"name": "Dabur India",                 "base": 540},
    "GODREJCP":      {"name": "Godrej Consumer Products",    "base": 1250},
    "HAVELLS":       {"name": "Havells India",               "base": 1650},
    "ICICIGI":       {"name": "ICICI General Insurance",     "base": 1800},
    "ICICIPRULI":    {"name": "ICICI Prudential Life",       "base": 650},
    "IOC":           {"name": "Indian Oil Corporation",      "base": 165},
    "IRCTC":         {"name": "IRCTC",                       "base": 780},
    "JINDALSTEL":    {"name": "Jindal Steel & Power",        "base": 920},
    "LTIM":          {"name": "LTIMindtree",                 "base": 5200},
    "LTTS":          {"name": "L&T Technology Services",     "base": 5500},
    "LUPIN":         {"name": "Lupin",                       "base": 1900},
    "MOTHERSON":     {"name": "Motherson Sumi Wiring",       "base": 185},
    "MUTHOOTFIN":    {"name": "Muthoot Finance",             "base": 1950},
    "NAUKRI":        {"name": "Info Edge (Naukri)",          "base": 7200},
    "NMDC":          {"name": "NMDC",                        "base": 230},
    "OFSS":          {"name": "Oracle Financial Services",   "base": 11000},
    "PAGEIND":       {"name": "Page Industries",             "base": 45000},
    "PIDILITIND":    {"name": "Pidilite Industries",         "base": 2900},
    "PIIND":         {"name": "PI Industries",               "base": 3800},
    "PNB":           {"name": "Punjab National Bank",        "base": 105},
    "RECLTD":        {"name": "REC Limited",                 "base": 480},
    "SAIL":          {"name": "Steel Authority of India",    "base": 130},
    "SIEMENS":       {"name": "Siemens",                     "base": 6500},
    "SRF":           {"name": "SRF",                         "base": 2400},
    "TATAPOWER":     {"name": "Tata Power",                  "base": 395},
    "TORNTPHARM":    {"name": "Torrent Pharmaceuticals",     "base": 3100},
    "TRENT":         {"name": "Trent",                       "base": 5500},
    "UBL":           {"name": "United Breweries",            "base": 1900},
    "UNIONBANK":     {"name": "Union Bank of India",         "base": 125},
    "UPL":           {"name": "UPL",                         "base": 540},
    "VBL":           {"name": "Varun Beverages",             "base": 1650},
    "VEDL":          {"name": "Vedanta",                     "base": 455},
    "ZOMATO":        {"name": "Zomato",                      "base": 240},
    "ZYDUSLIFE":     {"name": "Zydus Lifesciences",          "base": 1050},
    # Nifty Midcap 150
    "ABCAPITAL":     {"name": "Aditya Birla Capital",        "base": 195},
    "ABFRL":         {"name": "Aditya Birla Fashion",        "base": 295},
    "APLAPOLLO":     {"name": "APL Apollo Tubes",            "base": 1650},
    "AUBANK":        {"name": "AU Small Finance Bank",       "base": 740},
    "AUROPHARMA":    {"name": "Aurobindo Pharma",            "base": 1280},
    "BALKRISIND":    {"name": "Balkrishna Industries",       "base": 2800},
    "BANDHANBNK":    {"name": "Bandhan Bank",                "base": 185},
    "BATAINDIA":     {"name": "Bata India",                  "base": 1450},
    "BHARATFORG":    {"name": "Bharat Forge",                "base": 1250},
    "BIOCON":        {"name": "Biocon",                      "base": 360},
    "CESC":          {"name": "CESC",                        "base": 165},
    "COFORGE":       {"name": "Coforge",                     "base": 7500},
    "CONCOR":        {"name": "Container Corp",              "base": 990},
    "CROMPTON":      {"name": "Crompton Greaves Consumer",   "base": 380},
    "CUMMINSIND":    {"name": "Cummins India",               "base": 3400},
    "DALBHARAT":     {"name": "Dalmia Bharat",               "base": 1900},
    "DEEPAKNTR":     {"name": "Deepak Nitrite",              "base": 2500},
    "EMAMILTD":      {"name": "Emami",                       "base": 650},
    "ESCORTS":       {"name": "Escorts Kubota",              "base": 3500},
    "EXIDEIND":      {"name": "Exide Industries",            "base": 480},
    "FEDERALBNK":    {"name": "Federal Bank",                "base": 195},
    "GMRINFRA":      {"name": "GMR Airports Infrastructure", "base": 95},
    "GODREJPROP":    {"name": "Godrej Properties",           "base": 2600},
    "GRANULES":      {"name": "Granules India",              "base": 580},
    "GUJGASLTD":     {"name": "Gujarat Gas",                 "base": 550},
    "HAL":           {"name": "Hindustan Aeronautics",       "base": 4200},
    "HFCL":          {"name": "HFCL",                        "base": 125},
    "HINDPETRO":     {"name": "HPCL",                        "base": 380},
    "IDFCFIRSTB":    {"name": "IDFC First Bank",             "base": 75},
    "IEX":           {"name": "Indian Energy Exchange",      "base": 185},
    "INDHOTEL":      {"name": "Indian Hotels",               "base": 580},
    "INDIANB":       {"name": "Indian Bank",                 "base": 525},
    "INDUSTOWER":    {"name": "Indus Towers",                "base": 340},
    "INOXWIND":      {"name": "Inox Wind",                   "base": 185},
    "IREDA":         {"name": "IREDA",                       "base": 205},
    "IRFC":          {"name": "IRFC",                        "base": 185},
    "JKCEMENT":      {"name": "JK Cement",                   "base": 4200},
    "JSL":           {"name": "Jindal Stainless",            "base": 780},
    "JUBLFOOD":      {"name": "Jubilant FoodWorks",          "base": 620},
    "KALYANKJIL":    {"name": "Kalyan Jewellers",            "base": 550},
    "KPITTECH":      {"name": "KPIT Technologies",           "base": 1550},
    "LALPATHLAB":    {"name": "Dr Lal PathLabs",             "base": 2500},
    "LAURUSLABS":    {"name": "Laurus Labs",                 "base": 520},
    "LICHSGFIN":     {"name": "LIC Housing Finance",         "base": 680},
    "LTFOODS":       {"name": "LT Foods",                    "base": 380},
    "MARICO":        {"name": "Marico",                      "base": 650},
    "MAXHEALTH":     {"name": "Max Healthcare",              "base": 950},
    "MCX":           {"name": "Multi Commodity Exchange",    "base": 5200},
    "METROPOLIS":    {"name": "Metropolis Healthcare",       "base": 2000},
    "MFSL":          {"name": "Max Financial Services",      "base": 1100},
    "MSUMI":         {"name": "Motherson Sumi Systems",      "base": 185},
    "NATIONALUM":    {"name": "National Aluminium",          "base": 195},
    "NYKAA":         {"name": "FSN E-Commerce (Nykaa)",      "base": 195},
    "OBL":           {"name": "Orient Bell",                 "base": 380},
    "OBEROIRLTY":    {"name": "Oberoi Realty",               "base": 1850},
    "PATANJALI":     {"name": "Patanjali Foods",             "base": 1650},
    "PAYTM":         {"name": "One97 Communications",        "base": 850},
    "PERSISTENT":    {"name": "Persistent Systems",          "base": 5500},
    "PETRONET":      {"name": "Petronet LNG",                "base": 350},
    "POLYCAB":       {"name": "Polycab India",               "base": 6500},
    "PPLPHARMA":     {"name": "Piramal Pharma",              "base": 195},
    "PRESTIGE":      {"name": "Prestige Estates",            "base": 1650},
    "PVRINOX":       {"name": "PVR INOX",                    "base": 1450},
    "RAMCOCEM":      {"name": "Ramco Cements",               "base": 950},
    "RBLBANK":       {"name": "RBL Bank",                    "base": 195},
    "REDINGTON":     {"name": "Redington",                   "base": 220},
    "SCHAEFFLER":    {"name": "Schaeffler India",            "base": 4200},
    "SKFINDIA":      {"name": "SKF India",                   "base": 5800},
    "SOLARINDS":     {"name": "Solar Industries",            "base": 9500},
    "SONACOMS":      {"name": "Sona BLW Precision",          "base": 620},
    "STARHEALTH":    {"name": "Star Health Insurance",       "base": 580},
    "SUMICHEM":      {"name": "Sumitomo Chemical",           "base": 480},
    "SUNDARMFIN":    {"name": "Sundaram Finance",            "base": 4800},
    "SUNDRMFAST":    {"name": "Sundram Fasteners",           "base": 1350},
    "SUPREMEIND":    {"name": "Supreme Industries",          "base": 4800},
    "SYNGENE":       {"name": "Syngene International",       "base": 780},
    "TATACHEM":      {"name": "Tata Chemicals",              "base": 1050},
    "TATAELXSI":     {"name": "Tata Elxsi",                  "base": 7500},
    "TATATECH":      {"name": "Tata Technologies",           "base": 1050},
    "TIINDIA":       {"name": "Tube Investments",            "base": 3800},
    "TIMKEN":        {"name": "Timken India",                "base": 3500},
    "TORNTPOWER":    {"name": "Torrent Power",               "base": 1350},
    "TVSMOTOR":      {"name": "TVS Motor Company",           "base": 2500},
    "UCOBANK":       {"name": "UCO Bank",                    "base": 52},
    "ULTRACEMCO":    {"name": "UltraTech Cement",            "base": 9800},
    "UNITDSPR":      {"name": "United Spirits",              "base": 1350},
    "VGUARD":        {"name": "V-Guard Industries",          "base": 380},
    "VOLTAS":        {"name": "Voltas",                      "base": 1450},
    "WOCKPHARMA":    {"name": "Wockhardt",                   "base": 1250},
    "ZEEL":          {"name": "Zee Entertainment",           "base": 145},
    # Nifty Smallcap 250 (selected key stocks)
    "AAVAS":         {"name": "Aavas Financiers",            "base": 1850},
    "ABSLAMC":       {"name": "Aditya Birla Sun Life AMC",   "base": 620},
    "ACCELYA":       {"name": "Accelya Solutions",           "base": 1650},
    "AEGISLOG":      {"name": "Aegis Logistics",             "base": 480},
    "AIAENG":        {"name": "AIA Engineering",             "base": 3800},
    "AJANTPHARM":    {"name": "Ajanta Pharma",               "base": 2800},
    "ALKEM":         {"name": "Alkem Laboratories",          "base": 5200},
    "AMARAJABAT":    {"name": "Amara Raja Energy",           "base": 1050},
    "AMBER":         {"name": "Amber Enterprises",           "base": 4800},
    "ANURAS":        {"name": "Anupam Rasayan",              "base": 850},
    "APARINDS":      {"name": "Apar Industries",             "base": 8500},
    "APTUS":         {"name": "Aptus Value Housing",         "base": 350},
    "ARVINDFASN":    {"name": "Arvind Fashions",             "base": 380},
    "ASTRAL":        {"name": "Astral",                      "base": 1950},
    "ATUL":          {"name": "Atul",                        "base": 7500},
    "BASF":          {"name": "BASF India",                  "base": 5500},
    "BEML":          {"name": "BEML",                        "base": 3800},
    "BLUESTARCO":    {"name": "Blue Star",                   "base": 1950},
    "BRIGADE":       {"name": "Brigade Enterprises",         "base": 1050},
    "CAMPUS":        {"name": "Campus Activewear",           "base": 380},
    "CANFINHOME":    {"name": "Can Fin Homes",               "base": 780},
    "CARBORUNIV":    {"name": "Carborundum Universal",       "base": 1250},
    "CDSL":          {"name": "CDSL",                        "base": 1650},
    "CERA":          {"name": "Cera Sanitaryware",           "base": 8500},
    "CLEAN":         {"name": "Clean Science",               "base": 1350},
    "CRAFTSMAN":     {"name": "Craftsman Automation",        "base": 5500},
    "DATAMATICS":    {"name": "Datamatics Global",           "base": 680},
    "DCMSHRIRAM":    {"name": "DCM Shriram",                 "base": 1050},
    "DELHIVERY":     {"name": "Delhivery",                   "base": 380},
    "DEVYANI":       {"name": "Devyani International",       "base": 185},
    "DIXON":         {"name": "Dixon Technologies",          "base": 12500},
    "DOLLAR":        {"name": "Dollar Industries",           "base": 580},
    "EIDPARRY":      {"name": "EID Parry",                   "base": 780},
    "ELGIEQUIP":     {"name": "Elgi Equipments",             "base": 680},
    "EPIGRAL":       {"name": "Epigral",                     "base": 1350},
    "EQUITASBNK":    {"name": "Equitas Small Finance Bank",  "base": 85},
    "ESABINDIA":     {"name": "Esab India",                  "base": 4800},
    "ETHOSLTD":      {"name": "Ethos",                       "base": 2800},
    "FINEORG":       {"name": "Fine Organic Industries",     "base": 5200},
    "FMGOETZE":      {"name": "Federal-Mogul Goetze",        "base": 380},
    "GAEL":          {"name": "Gujarat Ambuja Exports",      "base": 265},
    "GALAXYSURF":    {"name": "Galaxy Surfactants",          "base": 3200},
    "GARFIBRES":     {"name": "Garware Technical Fibres",    "base": 3800},
    "GAYAPROJ":      {"name": "Gaya Projects",               "base": 95},
    "GESHIP":        {"name": "Great Eastern Shipping",      "base": 1050},
    "GILLETTE":      {"name": "Gillette India",              "base": 7500},
    "GLENMARK":      {"name": "Glenmark Pharmaceuticals",    "base": 1050},
    "GLOBUSSPR":     {"name": "Globus Spirits",              "base": 850},
    "GNFC":          {"name": "Gujarat Narmada Valley",      "base": 620},
    "GPPL":          {"name": "Gujarat Pipavav Port",        "base": 195},
    "GRINDWELL":     {"name": "Grindwell Norton",            "base": 2200},
    "HAPPSTMNDS":    {"name": "Happiest Minds Technologies", "base": 780},
    "HLEGLAS":       {"name": "HLE Glascoat",                "base": 380},
    "HOMEFIRST":     {"name": "Home First Finance",          "base": 1050},
    "HONAUT":        {"name": "Honeywell Automation",        "base": 45000},
    "HUDCO":         {"name": "HUDCO",                       "base": 195},
    "IDBI":          {"name": "IDBI Bank",                   "base": 85},
    "IDFCFIRSTB":    {"name": "IDFC First Bank",             "base": 75},
    "IGL":           {"name": "Indraprastha Gas",            "base": 450},
    "INDIAMART":     {"name": "IndiaMART InterMESH",         "base": 2500},
    "INDIGO":        {"name": "IndiGo (InterGlobe Aviation)","base": 4200},
    "INGERRAND":     {"name": "Ingersoll-Rand",              "base": 3200},
    "INTELLECT":     {"name": "Intellect Design Arena",      "base": 780},
    "IONEXCHANG":    {"name": "Ion Exchange",                "base": 1650},
    "IPCALAB":       {"name": "IPCA Laboratories",           "base": 1650},
    "ISEC":          {"name": "ICICI Securities",            "base": 780},
    "JBCHEPHARM":    {"name": "JB Chemicals",                "base": 1850},
    "JBMA":          {"name": "JBM Auto",                    "base": 1650},
    "JKPAPER":       {"name": "JK Paper",                    "base": 480},
    "JKTYRE":        {"name": "JK Tyre & Industries",        "base": 380},
    "JSWENERGY":     {"name": "JSW Energy",                  "base": 620},
    "JUSTDIAL":      {"name": "Just Dial",                   "base": 1050},
    "KAJARIACER":    {"name": "Kajaria Ceramics",            "base": 1350},
    "KAMDHENU":      {"name": "Kamdhenu",                    "base": 380},
    "KANSAINER":     {"name": "Kansai Nerolac Paints",       "base": 320},
    "KAYNES":        {"name": "Kaynes Technology",           "base": 3800},
    "KENNAMET":      {"name": "Kennametal India",            "base": 2500},
    "KFINTECH":      {"name": "KFin Technologies",           "base": 850},
    "KNR":           {"name": "KNR Constructions",           "base": 320},
    "KRBL":          {"name": "KRBL",                        "base": 380},
    "KSCL":          {"name": "Kaveri Seed Company",         "base": 780},
    "LATENTVIEW":    {"name": "LatentView Analytics",        "base": 480},
    "LEMONTREE":     {"name": "Lemon Tree Hotels",           "base": 145},
    "LXCHEM":        {"name": "Laxmi Organic Industries",    "base": 265},
    "MAHINDCIE":     {"name": "Mahindra CIE Automotive",     "base": 580},
    "MAPMYINDIA":    {"name": "CE Info Systems",             "base": 1650},
    "MCDOWELL-N":    {"name": "United Spirits",              "base": 1350},
    "MFSL":          {"name": "Max Financial Services",      "base": 1100},
    "MIDHANI":       {"name": "Mishra Dhatu Nigam",          "base": 320},
    "MINDACORP":     {"name": "Minda Corporation",           "base": 480},
    "MMFL":          {"name": "M&M Financial Services",      "base": 295},
    "MOLD-TEK":      {"name": "Mold-Tek Packaging",          "base": 850},
    "MRPL":          {"name": "MRPL",                        "base": 185},
    "NATCOPHARM":    {"name": "Natco Pharma",                "base": 1650},
    "NESCO":         {"name": "Nesco",                       "base": 950},
    "NETWORK18":     {"name": "Network18 Media",             "base": 85},
    "NIACL":         {"name": "New India Assurance",         "base": 195},
    "NOCIL":         {"name": "NOCIL",                       "base": 265},
    "NSLNISP":       {"name": "NMDC Steel",                  "base": 52},
    "OLECTRA":       {"name": "Olectra Greentech",           "base": 1350},
    "ORIENTCEM":     {"name": "Orient Cement",               "base": 265},
    "PGHH":          {"name": "Procter & Gamble Hygiene",    "base": 15000},
    "PHOENIXLTD":    {"name": "Phoenix Mills",               "base": 3200},
    "PNBHOUSING":    {"name": "PNB Housing Finance",         "base": 950},
    "POLYMED":       {"name": "Poly Medicure",               "base": 1950},
    "PRINCEPIPE":    {"name": "Prince Pipes",                "base": 620},
    "PRSMJOHNSN":    {"name": "Prism Johnson",               "base": 195},
    "PSPPROJECT":    {"name": "PSP Projects",                "base": 680},
    "QUESS":         {"name": "Quess Corp",                  "base": 580},
    "RADICO":        {"name": "Radico Khaitan",              "base": 1850},
    "RAILVIKAS":     {"name": "Rail Vikas Nigam",            "base": 520},
    "RAJRATAN":      {"name": "Rajratan Global Wire",        "base": 850},
    "RALLIS":        {"name": "Rallis India",                "base": 295},
    "RAYMOND":       {"name": "Raymond",                     "base": 1950},
    "RITES":         {"name": "RITES",                       "base": 620},
    "ROSSARI":       {"name": "Rossari Biotech",             "base": 780},
    "ROUTE":         {"name": "Route Mobile",                "base": 1450},
    "RPSGVENT":      {"name": "RPSG Ventures",               "base": 850},
    "SAFARI":        {"name": "Safari Industries",           "base": 2800},
    "SAREGAMA":      {"name": "Saregama India",              "base": 480},
    "SBICARD":       {"name": "SBI Cards",                   "base": 780},
    "SENCO":         {"name": "Senco Gold",                  "base": 1050},
    "SHYAMMETL":     {"name": "Shyam Metalics",              "base": 620},
    "SOBHA":         {"name": "Sobha",                       "base": 1650},
    "SPARC":         {"name": "Sun Pharma Advanced Research","base": 380},
    "SPANDANA":      {"name": "Spandana Sphoorty",           "base": 780},
    "SPORTKING":     {"name": "Sportking India",             "base": 850},
    "STLTECH":       {"name": "Sterlite Technologies",       "base": 195},
    "STYLAMIND":     {"name": "Stylam Industries",           "base": 1650},
    "SUBROS":        {"name": "Subros",                      "base": 620},
    "SUDARSCHEM":    {"name": "Sudarshan Chemical",          "base": 1050},
    "SUPRIYA":       {"name": "Supriya Lifescience",         "base": 480},
    "SUVEN":         {"name": "Suven Pharmaceuticals",       "base": 1050},
    "SWSOLAR":       {"name": "Sterling and Wilson",         "base": 480},
    "SYMPHONY":      {"name": "Symphony",                    "base": 1050},
    "TANLA":         {"name": "Tanla Platforms",             "base": 950},
    "TASTYBITE":     {"name": "Tasty Bite Eatables",         "base": 15000},
    "TATAINVEST":    {"name": "Tata Investment Corp",        "base": 6500},
    "TEJASNET":      {"name": "Tejas Networks",              "base": 950},
    "THYROCARE":     {"name": "Thyrocare Technologies",      "base": 650},
    "TIMESCAN":      {"name": "Time Technoplast",            "base": 380},
    "TIMETECHNO":    {"name": "Time Technoplast",            "base": 380},
    "TIPSINDLTD":    {"name": "Tips Industries",             "base": 950},
    "TRIDENT":       {"name": "Trident",                     "base": 52},
    "TRITURBINE":    {"name": "Triveni Turbine",             "base": 620},
    "UNIPARTS":      {"name": "Uniparts India",              "base": 620},
    "UTIAMC":        {"name": "UTI AMC",                     "base": 1050},
    "VIPIND":        {"name": "VIP Industries",              "base": 480},
    "VINATIORGA":    {"name": "Vinati Organics",             "base": 1950},
    "VSTIND":        {"name": "VST Industries",              "base": 4200},
    "WELCORP":       {"name": "Welspun Corp",                "base": 620},
    "WELSPUNLIV":    {"name": "Welspun Living",              "base": 195},
    "WESTLIFE":      {"name": "Westlife Foodworld",          "base": 850},
    "WHIRLPOOL":     {"name": "Whirlpool of India",          "base": 1650},
    "WONDERLA":      {"name": "Wonderla Holidays",           "base": 850},
    "XPROINDIA":     {"name": "Xpro India",                  "base": 480},
    "YATHARTH":      {"name": "Yatharth Hospital",           "base": 620},
    "ZENTEC":        {"name": "Zen Technologies",            "base": 1950},
    "ZENSARTECH":    {"name": "Zensar Technologies",         "base": 680},
    "360ONE": {"name": "360 ONE WAM Ltd.", "base": 100},
    "3MINDIA": {"name": "3M India Ltd.", "base": 100},
    "AADHARHFC": {"name": "Aadhar Housing Finance Ltd.", "base": 100},
    "AARTIIND": {"name": "Aarti Industries Ltd.", "base": 100},
    "ABB": {"name": "ABB India Ltd.", "base": 100},
    "ABBOTINDIA": {"name": "Abbott India Ltd.", "base": 100},
    "ABDL": {"name": "Allied Blenders and Distillers Ltd.", "base": 100},
    "ACC": {"name": "ACC Ltd.", "base": 100},
    "ACE": {"name": "Action Construction Equipment Ltd.", "base": 100},
    "ACMESOLAR": {"name": "ACME Solar Holdings Ltd.", "base": 100},
    "ADANIENSOL": {"name": "Adani Energy Solutions Ltd.", "base": 100},
    "AFFLE": {"name": "Affle India Ltd.", "base": 100},
    "AIIL": {"name": "Authum Investment Infrastructure Ltd.", "base": 100},
    "ANANDRATHI": {"name": "Anand Rathi Wealth Ltd.", "base": 100},
    "ANANTRAJ": {"name": "Anant Raj Ltd.", "base": 100},
    "ANGELONE": {"name": "Angel One Ltd.", "base": 100},
    "ANTHEM": {"name": "Anthem Biosciences Ltd.", "base": 100},
    "APOLLOTYRE": {"name": "Apollo Tyres Ltd.", "base": 100},
    "ASAHIINDIA": {"name": "Asahi India Glass Ltd.", "base": 100},
    "ASHOKLEY": {"name": "Ashok Leyland Ltd.", "base": 100},
    "ASTERDM": {"name": "Aster DM Healthcare Ltd.", "base": 100},
    "ATHERENERG": {"name": "Ather Energy Ltd.", "base": 100},
    "BAJAJHFL": {"name": "Bajaj Housing Finance Ltd.", "base": 100},
    "BALRAMCHIN": {"name": "Balrampur Chini Mills Ltd.", "base": 100},
    "BANKINDIA": {"name": "Bank of India", "base": 100},
    "BAYERCROP": {"name": "Bayer Cropscience Ltd.", "base": 100},
    "BBTC": {"name": "Bombay Burmah Trading Corp.", "base": 100},
    "BDL": {"name": "Bharat Dynamics Ltd.", "base": 100},
    "BELRISE": {"name": "Belrise Industries Ltd.", "base": 100},
    "BHARTIHEXA": {"name": "Bharti Hexacom Ltd.", "base": 100},
    "BIKAJI": {"name": "Bikaji Foods International Ltd.", "base": 100},
    "BLS": {"name": "BLS International Services Ltd.", "base": 100},
    "BLUEDART": {"name": "Blue Dart Express Ltd.", "base": 100},
    "BLUEJET": {"name": "Blue Jet Healthcare Ltd.", "base": 100},
    "BSE": {"name": "BSE Ltd.", "base": 100},
    "BSOFT": {"name": "Birlasoft Ltd.", "base": 100},
    "CAMS": {"name": "Computer Age Management Services Ltd.", "base": 100},
    "CANHLIFE": {"name": "Canara HSBC Life Insurance Ltd.", "base": 100},
    "CAPLIPOINT": {"name": "Caplin Point Laboratories Ltd.", "base": 100},
    "CARTRADE": {"name": "Cartrade Tech Ltd.", "base": 100},
    "CASTROLIND": {"name": "Castrol India Ltd.", "base": 100},
    "CCL": {"name": "CCL Products India Ltd.", "base": 100},
    "CEATLTD": {"name": "Ceat Ltd.", "base": 100},
    "CENTRALBK": {"name": "Central Bank of India", "base": 100},
    "CGCL": {"name": "Capri Global Capital Ltd.", "base": 100},
    "CGPOWER": {"name": "CG Power and Industrial Solutions Ltd.", "base": 100},
    "CHALET": {"name": "Chalet Hotels Ltd.", "base": 100},
    "CHAMBLFERT": {"name": "Chambal Fertilizers and Chemicals Ltd.", "base": 100},
    "CHENNPETRO": {"name": "Chennai Petroleum Corporation Ltd.", "base": 100},
    "CHOLAHLDNG": {"name": "Cholamandalam Financial Holdings Ltd.", "base": 100},
    "CIEINDIA": {"name": "CIE Automotive India Ltd.", "base": 100},
    "COCHINSHIP": {"name": "Cochin Shipyard Ltd.", "base": 100},
    "COHANCE": {"name": "Cohance Lifesciences Ltd.", "base": 100},
    "CONCORDBIO": {"name": "Concord Biotech Ltd.", "base": 100},
    "COROMANDEL": {"name": "Coromandel International Ltd.", "base": 100},
    "CREDITACC": {"name": "CreditAccess Grameen Ltd.", "base": 100},
    "CRISIL": {"name": "CRISIL Ltd.", "base": 100},
    "CUB": {"name": "City Union Bank Ltd.", "base": 100},
    "CYIENT": {"name": "Cyient Ltd.", "base": 100},
    "DATAPATTNS": {"name": "Data Patterns India Ltd.", "base": 100},
    "DEEPAKFERT": {"name": "Deepak Fertilisers and Petrochemicals Ltd.", "base": 100},
    "DMART": {"name": "Avenue Supermarts Ltd.", "base": 100},
    "DOMS": {"name": "DOMS Industries Ltd.", "base": 100},
    "ECLERX": {"name": "eClerx Services Ltd.", "base": 100},
    "EIHOTEL": {"name": "EIH Ltd.", "base": 100},
    "ELECON": {"name": "Elecon Engineering Co. Ltd.", "base": 100},
    "EMCURE": {"name": "Emcure Pharmaceuticals Ltd.", "base": 100},
    "EMMVEE": {"name": "Emmvee Photovoltaic Power Ltd.", "base": 100},
    "ENDURANCE": {"name": "Endurance Technologies Ltd.", "base": 100},
    "ENGINERSIN": {"name": "Engineers India Ltd.", "base": 100},
    "ENRIN": {"name": "Siemens Energy India Ltd.", "base": 100},
    "ERIS": {"name": "Eris Lifesciences Ltd.", "base": 100},
    "ETERNAL": {"name": "Eternal Ltd.", "base": 100},
    "FACT": {"name": "Fertilisers and Chemicals Travancore Ltd.", "base": 100},
    "FINCABLES": {"name": "Finolex Cables Ltd.", "base": 100},
    "FIRSTCRY": {"name": "Brainbees Solutions Ltd.", "base": 100},
    "FIVESTAR": {"name": "Five Star Business Finance Ltd.", "base": 100},
    "FLUOROCHEM": {"name": "Gujarat Fluorochemicals Ltd.", "base": 100},
    "FORCEMOT": {"name": "Force Motors Ltd.", "base": 100},
    "FORTIS": {"name": "Fortis Healthcare Ltd.", "base": 100},
    "FSL": {"name": "Firstsource Solutions Ltd.", "base": 100},
    "GABRIEL": {"name": "Gabriel India Ltd.", "base": 100},
    "GAIL": {"name": "GAIL India Ltd.", "base": 100},
    "GALLANTT": {"name": "Gallantt Ispat Ltd.", "base": 100},
    "GICRE": {"name": "General Insurance Corporation of India", "base": 100},
    "GLAND": {"name": "Gland Pharma Ltd.", "base": 100},
    "GLAXO": {"name": "Glaxosmithkline Pharmaceuticals Ltd.", "base": 100},
    "GMDCLTD": {"name": "Gujarat Mineral Development Corporation Ltd.", "base": 100},
    "GMRAIRPORT": {"name": "GMR Airports Ltd.", "base": 100},
    "GODFRYPHLP": {"name": "Godfrey Phillips India Ltd.", "base": 100},
    "GODIGIT": {"name": "Go Digit General Insurance Ltd.", "base": 100},
    "GODREJIND": {"name": "Godrej Industries Ltd.", "base": 100},
    "GPIL": {"name": "Godawari Power and Ispat Ltd.", "base": 100},
    "GRAPHITE": {"name": "Graphite India Ltd.", "base": 100},
    "GRAVITA": {"name": "Gravita India Ltd.", "base": 100},
    "GROWW": {"name": "Billionbrains Garage Ventures Ltd.", "base": 100},
    "GRSE": {"name": "Garden Reach Shipbuilders and Engineers Ltd.", "base": 100},
    "HBLENGINE": {"name": "HBL Engineering Ltd.", "base": 100},
    "HDBFS": {"name": "HDB Financial Services Ltd.", "base": 100},
    "HDFCAMC": {"name": "HDFC Asset Management Company Ltd.", "base": 100},
    "HEG": {"name": "HEG Ltd.", "base": 100},
    "HEXT": {"name": "Hexaware Technologies Ltd.", "base": 100},
    "HINDCOPPER": {"name": "Hindustan Copper Ltd.", "base": 100},
    "HINDZINC": {"name": "Hindustan Zinc Ltd.", "base": 100},
    "HONASA": {"name": "Honasa Consumer Ltd.", "base": 100},
    "HSCL": {"name": "Himadri Speciality Chemical Ltd.", "base": 100},
    "HYUNDAI": {"name": "Hyundai Motor India Ltd.", "base": 100},
    "ICICIAMC": {"name": "ICICI Prudential Asset Management Co. Ltd.", "base": 100},
    "IDEA": {"name": "Vodafone Idea Ltd.", "base": 100},
    "IFCI": {"name": "IFCI Ltd.", "base": 100},
    "IGIL": {"name": "International Gemological Institute Ltd.", "base": 100},
    "IIFL": {"name": "IIFL Finance Ltd.", "base": 100},
    "IKS": {"name": "Inventurus Knowledge Solutions Ltd.", "base": 100},
    "INDGN": {"name": "Indegene Ltd.", "base": 100},
    "INDIACEM": {"name": "India Cements Ltd.", "base": 100},
    "IOB": {"name": "Indian Overseas Bank", "base": 100},
    "IRB": {"name": "IRB Infrastructure Developers Ltd.", "base": 100},
    "IRCON": {"name": "IRCON International Ltd.", "base": 100},
    "ITCHOTELS": {"name": "ITC Hotels Ltd.", "base": 100},
    "ITI": {"name": "ITI Ltd.", "base": 100},
    "JAINREC": {"name": "Jain Resource Recycling Ltd.", "base": 100},
    "JINDALSAW": {"name": "Jindal Saw Ltd.", "base": 100},
    "JIOFIN": {"name": "Jio Financial Services Ltd.", "base": 100},
    "JMFINANCIL": {"name": "JM Financial Ltd.", "base": 100},
    "JPPOWER": {"name": "Jaiprakash Power Ventures Ltd.", "base": 100},
    "JSWCEMENT": {"name": "JSW Cement Ltd.", "base": 100},
    "JSWINFRA": {"name": "JSW Infrastructure Ltd.", "base": 100},
    "JUBLINGREA": {"name": "Jubilant Ingrevia Ltd.", "base": 100},
    "JUBLPHARMA": {"name": "Jubilant Pharmova Ltd.", "base": 100},
    "JWL": {"name": "Jupiter Wagons Ltd.", "base": 100},
    "JYOTICNC": {"name": "Jyoti CNC Automation Ltd.", "base": 100},
    "KARURVYSYA": {"name": "Karur Vysya Bank Ltd.", "base": 100},
    "KEC": {"name": "KEC International Ltd.", "base": 100},
    "KEI": {"name": "KEI Industries Ltd.", "base": 100},
    "KIMS": {"name": "Krishna Institute of Medical Sciences Ltd.", "base": 100},
    "KIRLOSENG": {"name": "Kirloskar Oil Engines Ltd.", "base": 100},
    "KPIL": {"name": "Kalpataru Projects International Ltd.", "base": 100},
    "KPRMILL": {"name": "KPR Mill Ltd.", "base": 100},
    "LICI": {"name": "Life Insurance Corporation of India", "base": 100},
    "LINDEINDIA": {"name": "Linde India Ltd.", "base": 100},
    "LLOYDSME": {"name": "Lloyds Metals and Energy Ltd.", "base": 100},
    "LODHA": {"name": "Lodha Developers Ltd.", "base": 100},
    "LTF": {"name": "L and T Finance Ltd.", "base": 100},
    "MAHABANK": {"name": "Bank of Maharashtra", "base": 100},
    "MANAPPURAM": {"name": "Manappuram Finance Ltd.", "base": 100},
    "MANKIND": {"name": "Mankind Pharma Ltd.", "base": 100},
    "MAZDOCK": {"name": "Mazagon Dock Shipbuilders Ltd.", "base": 100},
    "MEDANTA": {"name": "Global Health Ltd.", "base": 100},
    "MGL": {"name": "Mahanagar Gas Ltd.", "base": 100},
    "MMTC": {"name": "MMTC Ltd.", "base": 100},
    "MOTILALOFS": {"name": "Motilal Oswal Financial Services Ltd.", "base": 100},
    "MPHASIS": {"name": "MphasiS Ltd.", "base": 100},
    "MRF": {"name": "MRF Ltd.", "base": 100},
    "NAVA": {"name": "Nava Ltd.", "base": 100},
    "NAVINFLUOR": {"name": "Navin Fluorine International Ltd.", "base": 100},
    "NBCC": {"name": "NBCC India Ltd.", "base": 100},
    "NCC": {"name": "NCC Ltd.", "base": 100},
    "NETWEB": {"name": "Netweb Technologies India Ltd.", "base": 100},
    "NEULANDLAB": {"name": "Neuland Laboratories Ltd.", "base": 100},
    "NEWGEN": {"name": "Newgen Software Technologies Ltd.", "base": 100},
    "NH": {"name": "Narayana Hrudayalaya Ltd.", "base": 100},
    "NHPC": {"name": "NHPC Ltd.", "base": 100},
    "NIVABUPA": {"name": "Niva Bupa Health Insurance Co. Ltd.", "base": 100},
    "NLCINDIA": {"name": "NLC India Ltd.", "base": 100},
    "NTPCGREEN": {"name": "NTPC Green Energy Ltd.", "base": 100},
    "NUVAMA": {"name": "Nuvama Wealth Management Ltd.", "base": 100},
    "NUVOCO": {"name": "Nuvoco Vistas Corporation Ltd.", "base": 100},
    "OIL": {"name": "Oil India Ltd.", "base": 100},
    "OLAELEC": {"name": "Ola Electric Mobility Ltd.", "base": 100},
    "PARADEEP": {"name": "Paradeep Phosphates Ltd.", "base": 100},
    "PCBL": {"name": "PCBL Chemical Ltd.", "base": 100},
    "PFC": {"name": "Power Finance Corporation Ltd.", "base": 100},
    "PFIZER": {"name": "Pfizer Ltd.", "base": 100},
    "PGEL": {"name": "PG Electroplast Ltd.", "base": 100},
    "PINELABS": {"name": "Pine Labs Ltd.", "base": 100},
    "PIRAMALFIN": {"name": "Piramal Finance Ltd.", "base": 100},
    "POLICYBZR": {"name": "PB Fintech Ltd.", "base": 100},
    "POONAWALLA": {"name": "Poonawalla Fincorp Ltd.", "base": 100},
    "PREMIERENE": {"name": "Premier Energies Ltd.", "base": 100},
    "PTCIL": {"name": "PTC Industries Ltd.", "base": 100},
    "RAILTEL": {"name": "Railtel Corporation of India Ltd.", "base": 100},
    "RAINBOW": {"name": "Rainbow Childrens Medicare Ltd.", "base": 100},
    "RHIM": {"name": "RHI Magnesita India Ltd.", "base": 100},
    "RKFORGE": {"name": "Ramkrishna Forgings Ltd.", "base": 100},
    "RPOWER": {"name": "Reliance Power Ltd.", "base": 100},
    "RRKABEL": {"name": "R R Kabel Ltd.", "base": 100},
    "RVNL": {"name": "Rail Vikas Nigam Ltd.", "base": 100},
    "SAGILITY": {"name": "Sagility Ltd.", "base": 100},
    "SAILIFE": {"name": "Sai Life Sciences Ltd.", "base": 100},
    "SAPPHIRE": {"name": "Sapphire Foods India Ltd.", "base": 100},
    "SARDAEN": {"name": "Sarda Energy and Minerals Ltd.", "base": 100},
    "SBFC": {"name": "SBFC Finance Ltd.", "base": 100},
    "SCHNEIDER": {"name": "Schneider Electric Infrastructure Ltd.", "base": 100},
    "SCI": {"name": "Shipping Corporation of India Ltd.", "base": 100},
    "SHREECEM": {"name": "Shree Cement Ltd.", "base": 100},
    "SIGNATURE": {"name": "Signatureglobal India Ltd.", "base": 100},
    "SJVN": {"name": "SJVN Ltd.", "base": 100},
    "SONATSOFTW": {"name": "Sonata Software Ltd.", "base": 100},
    "SUNTV": {"name": "Sun TV Network Ltd.", "base": 100},
    "SUZLON": {"name": "Suzlon Energy Ltd.", "base": 100},
    "SYRMA": {"name": "Syrma SGS Technology Ltd.", "base": 100},
    "TARIL": {"name": "Transformers and Rectifiers India Ltd.", "base": 100},
    "TATACAP": {"name": "Tata Capital Ltd.", "base": 100},
    "TATACOMM": {"name": "Tata Communications Ltd.", "base": 100},
    "TBOTEK": {"name": "TBO Tek Ltd.", "base": 100},
    "TECHNOE": {"name": "Techno Electric and Engineering Co. Ltd.", "base": 100},
    "TEGA": {"name": "Tega Industries Ltd.", "base": 100},
    "THELEELA": {"name": "Leela Palaces Hotels and Resorts Ltd.", "base": 100},
    "THERMAX": {"name": "Thermax Ltd.", "base": 100},
    "TITAGARH": {"name": "Titagarh Rail Systems Ltd.", "base": 100},
    "UNOMINDA": {"name": "UNO Minda Ltd.", "base": 100},
    "USHAMART": {"name": "Usha Martin Ltd.", "base": 100},
    "VIJAYA": {"name": "Vijaya Diagnostic Centre Ltd.", "base": 100},
    "VMM": {"name": "Vishal Mega Mart Ltd.", "base": 100},
    "VTL": {"name": "Vardhman Textiles Ltd.", "base": 100},
    "WAAREEENER": {"name": "Waaree Energies Ltd.", "base": 100},
    "YESBANK": {"name": "Yes Bank Ltd.", "base": 100},
    "ZFCVINDIA": {"name": "ZF Commercial Vehicle Control Systems India Ltd.", "base": 100},
    "ZYDUSWELL": {"name": "Zydus Wellness Ltd.", "base": 100},
}

# Use NIFTY500 as the main dict
NIFTY50 = NIFTY500
SYMBOLS = list(NIFTY500.keys())

# ── Interval seconds map ───────────────────────────────────────────────────────
INTERVAL_SECONDS = {
    "1minute":   60,
    "2minute":   120,
    "3minute":   180,
    "4minute":   240,
    "5minute":   300,
    "10minute":  600,
    "15minute":  900,
    "30minute":  1800,
    "1hour":     3600,
    "2hour":     7200,
    "4hour":     14400,
    "1day":      86400,
    "1week":     604800,
    "1month":    2592000,
    "1year":     31536000,
    "5year":     157680000,
}

INTERVALS = list(INTERVAL_SECONDS.keys())